### ISSUE TITLE
request to transfer java-loggertracer under opentracing-contrib umbrella

### ISSUE THREAD

**Issue by davidB** [opentracing-contrib/meta#14]
Hi,

I setup the project https://github.com/davidB/java-loggertracer, and would like to transfer it under opentracing-contrib umbrella.

Review and better name are welcome.

**Comment by pavolloffay** [comment]
Hi @davidB, 

I had a quick look at it, correct me if I am wrong. It does not depend on any specific logging framework e.g. `slf4j` reporter can be moved to a separate module (with dep on jackson).

**Comment by bhs** [comment]
@davidB thanks for donating this :)

I think `java-loggertracer` is a reasonable, self-descriptive name. Since repos can always be renamed, I decided to _carpe diem_ and created https://github.com/opentracing-contrib/java-loggertracer/invitations for you.

Please @-mention myself and @pavolloffay on your initial PR.

To be clear, you are an admin on this new repo and can run your own show there in terms of when merges happen, etc. Though I would recommend getting real / meaningful reviews at first while the groundwork is being established.

**Comment by davidB** [comment]
@bhs ,

About initial PR (migration), it's easier (for me) to push from my local clone of https://github.com/davidB/java-loggertracer to the new remote repo, than to create a PR (in fact I don't know how to create a PR between 2 repos that have no fork relation. If you know a simple way to make it, tell me.

@pavolloffay ,

 You're right since today, I introduce Reporter as abstraction to report to slf4j or other system (I'll probalbly provide a prometheus reporter). So each Reporter could be move to separated module, jar.
But as starting point, I prefer to include Reporter and define its dependency in scope provided (except for jackson). It's simpler for developpement and not more works for user.

Thanks

**Comment by davidB** [comment]
@bhs ,

I 'll fork the new repo, and push to my fork.

**Comment by davidB** [comment]
Ah, I trashed my local and remote repo/copy :-(
